server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fincore_db
    username: postgres
    password: fincore123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
